spring:
  application:
    name: Ebenezer
  datasource:
    url: jdbc:postgresql://localhost:5432/ebenezer
    username: pcodes
    password: pcodes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 211915901556-gvgjs77gbt029f0jkurm99je92qc1scl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json, text/html
application:
  app:
    frontend-url: http://localhost:3000
  file:
    uploads:
      media-output-path: ./uploads
  jwt:
    secret: 8wWYjFpCy6Otp48mdnWDgkTjt5IjPPJqAKpqKhzAEZM=
    expiration: 86400000 #24 hours
    refresh-token:
      expiration: 604800000 #7 days
  oauth2:
    redirect-url: http://localhost:3000/oauth2/redirect
